//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSkeleton.UserModule.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotnetSkeleton.UserModule.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Email_Is_Required {
            get {
                return ResourceManager.GetString("Email_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DC8 Framework] Welcome onboard!!!.
        /// </summary>
        public static string Email_Subject_Create_Account_Successfully {
            get {
                return ResourceManager.GetString("Email_Subject_Create_Account_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DC8 Framework] Forgot Password Request.
        /// </summary>
        public static string Email_Subject_Forgot_Password {
            get {
                return ResourceManager.GetString("Email_Subject_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please double-check and try again..
        /// </summary>
        public static string Incorrect_Password {
            get {
                return ResourceManager.GetString("Incorrect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be a negative number or 0..
        /// </summary>
        public static string Invalid_Request {
            get {
                return ResourceManager.GetString("Invalid_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role ..
        /// </summary>
        public static string Invalid_Role {
            get {
                return ResourceManager.GetString("Invalid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string Invalid_Token {
            get {
                return ResourceManager.GetString("Invalid_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions must not be empty..
        /// </summary>
        public static string Permissions_Not_Empty {
            get {
                return ResourceManager.GetString("Permissions_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Feature not found..
        /// </summary>
        public static string This_Feature_Not_Found {
            get {
                return ResourceManager.GetString("This_Feature_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permission already exists. Please choose a different role or permission..
        /// </summary>
        public static string This_Permission_Already_Exists {
            get {
                return ResourceManager.GetString("This_Permission_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permission has been deactivated. Please contact support for assistance..
        /// </summary>
        public static string This_Permission_Has_Been_Deactivated {
            get {
                return ResourceManager.GetString("This_Permission_Has_Been_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not found. Please verify the role name and try again..
        /// </summary>
        public static string This_Permission_Not_Found {
            get {
                return ResourceManager.GetString("This_Permission_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role already exists. Please choose a different role or permission..
        /// </summary>
        public static string This_Role_Already_Exists {
            get {
                return ResourceManager.GetString("This_Role_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role permission has been deactivated. Please contact support for assistance..
        /// </summary>
        public static string This_Role_Has_Been_Deactivated {
            get {
                return ResourceManager.GetString("This_Role_Has_Been_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found. Please verify the role name and try again..
        /// </summary>
        public static string This_Role_Not_Found {
            get {
                return ResourceManager.GetString("This_Role_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role permission already exists. Please choose a different role or permission..
        /// </summary>
        public static string This_RolePermission_Already_Exists {
            get {
                return ResourceManager.GetString("This_RolePermission_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role permission has been deactivated. Please contact support for assistance..
        /// </summary>
        public static string This_RolePermission_Has_Been_Deactivated {
            get {
                return ResourceManager.GetString("This_RolePermission_Has_Been_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission not found. Please verify the role permission and try again..
        /// </summary>
        public static string This_RolePermission_Not_Found {
            get {
                return ResourceManager.GetString("This_RolePermission_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists. Please choose a different username or email or phone number..
        /// </summary>
        public static string This_User_Already_Exists {
            get {
                return ResourceManager.GetString("This_User_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been deactivated. Please contact support for assistance..
        /// </summary>
        public static string This_User_Has_Been_Deactivated {
            get {
                return ResourceManager.GetString("This_User_Has_Been_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&apos;t find your account. Please double-check your login information and try again. If you need further assistance, please contact support..
        /// </summary>
        public static string This_User_Not_Found {
            get {
                return ResourceManager.GetString("This_User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
