global using Asp.Versioning;
global using Microsoft.AspNetCore.Localization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ApplicationModels;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using System.Globalization;
global using System.Text.Json;
global using System.Text.Json.Serialization;
