FROM node:20-alpine

RUN mkdir -p /home/app

COPY . /home/app

WORKDIR /home/app

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*

RUN npm install

RUN npm install pm2 -g

CMD ["pm2-runtime", "pm2-process.development.yml"]